spring:
  application:
    name: account-opening
  profiles:
    default: local

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

integration:
  core-banking:
    base-url: ${CORE_BANKING_BASE_URL:http://localhost:8082}
