package com.digitalbank.accountopening.audit;

public enum AuditAction {
    APPLICATION_CREATED,
    APPLICATION_SUBMITTED,
    KYC_CHECK_SUCCEEDED,
    KYC_CHECK_FAILED,
    APPLICATION_PROCESSED,
    APPROVAL_CASE_CREATED,
    APPROVAL_CASE_ASSIGNED,
    APPROVAL_CASE_APPROVED,
    APPROVAL_CASE_REJECTED,
    ACCOUNT_CREATION_STARTED,
    ACCOUNT_CREATION_RETRY_STARTED,
    ACCOUNT_CREATION_RETRY_PENDING,
    ACCOUNT_CREATION_FAILED,
    ACCOUNT_CREATED
}
